# Generated by Django 4.2.11 on 2024-05-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_voucher_referralwallet_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
